algoritmo "SOMAINTEIROS"
//Algoritmo para efetuar a soma de números inteiros
var
      A,B,X:inteiro
inicio
//Entraada de dados feita pelo usuário.
      Escreva("Digite o primeiro número: ")
      Leia(A)
      Escreva("Digite o segundo número: ")
      Leia(B)
//Equação de soma entre duas variáveis.
      X <- A+B
//Resultado aparecendo na tela para o usuário.
      Escreva("O resultado da soma dos dois valores apresentados é ",X)
fimalgoritmo