Algoritmo "Conversor de Reais/Dolares"
//Algoritmo para simular conversão de reais em dolares.
Var
   R, D:real

Inicio
   //Entrada de dados feita pelo usuário
   Escreva("Digite quantos Reais(R$) você possui na carteira: ")
   Leia(R)
   //Equação de conversão de reais em dolar
   D <- R/3.45
   //Saída de dados para o usuário
   Escreval
   Escreva("Você possui U$ ", D:1:2,".")
   escreval
Fimalgoritmo