Algoritmo "semnome"
//Algoritmo criado para converter de Fahrenheit para Celsius.
Var
   F,C:real

Inicio
   //Entrada de dados das temperaturas feitas pelo usuário.
   Escreva("Qual é a temperatura em Fahrenheit? ")
   Leia(F)
   //Equação de conversão de F para C.
   C <- (F - 32)/1.8
   //Saída de dados para usuário verificar o resultado.
   Escreva("A temperatura em graus celsius é ", C,".")

Fimalgoritmo